version: 0.0.{build}
image: Visual Studio 2017

clone_folder: c:\projects\pythonirbis

environment:
  PYTHON: C:\Python36-x64\python.exe
  PIP: C:\Python36-x64\Scripts\pip.exe
  COVERAGE: C:\Python36-x64\Scripts\coverage.exe
  TWINE: C:\Python36-x64\Scripts\twine.exe
  TWINE_USERNAME: amironov73
  TWINE_PASSWORD: 1JY9Dr54nOTpD3EAV4mqMQ==
  TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/

install:
  -cmd: %PYTHON% -m pip install --upgrade pip
  -cmd: %PIP% install --upgrade setuptools wheel coverage mypy

before_build:
  -cmd: %PYTHON% utils\patch_version.py pyirbis\__init__.py %APPVEYOR_BUILD_VERSION%
  -cmd: %PYTHON% utils\patch_version.py setup.py %APPVEYOR_BUILD_VERSION%

build_script:
  -cmd: %PYTHON% -m mypy pyirbis\core.py
  -cmd: %PYTHON% -m mypy pyirbis\ext.py

after_build:
  -cmd: %PYTHON% setup.py sdist bdist_wheel

test_script:
  -cmd: %COVERAGE% run tests\offline_tests.py
  -cmd: %COVERAGE% report
  -cmd: %COVERAGE% html

after_test:
  -cmd: %TWINE% upload dist/*

artifacts:
  - path: htmlcov
    name: Coverage
  - path: dist
    name: dist
