version: 0.0.{build}
image: Visual Studio 2017

clone_folder: c:\projects\pythonirbis

environment:
  PATH: C:\Python36-x64;C:\Python36-x64\Scripts;%PATH%
  PYTHON: C:\Python36-x64\python.exe
  PIP: C:\Python36-x64\Scripts\pip.exe
  COVERAGE: C:\Python36-x64\Scripts\coverage.exe
  TWINE: C:\Python36-x64\Scripts\twine.exe
  TWINE_USERNAME: amironov73
  TWINE_PASSWORD: 1JY9Dr54nOTpD3EAV4mqMQ==
  TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/

install:
  -cmd: python -m pip install --upgrade pip
  -cmd: pip install --upgrade setuptools wheel coverage mypy

before_build:
  -cmd: python utils\patch_version.py pyirbis\__init__.py %APPVEYOR_BUILD_VERSION%
  -cmd: python utils\patch_version.py setup.py %APPVEYOR_BUILD_VERSION%

build_script:
  -cmd: cd c:\projects\pythonirbis
  -cmd: python -m mypy pyirbis\core.py
  -cmd: python -m mypy pyirbis\ext.py

after_build:
  -cmd: cd c:\projects\pythonirbis
  -cmd: python setup.py sdist bdist_wheel

test_script:
  -cmd: cd c:\projects\pythonirbis
  -cmd: coverage run tests\offline_tests.py
  -cmd: coverage report
  -cmd: coverage html

after_test:
  -cmd: cd c:\projects\pythonirbis
  -cmd: twine upload dist/*

artifacts:
  - path: htmlcov
    name: Coverage
  - path: dist
    name: dist
