version: 0.0.{build}
image: Visual Studio 2017

clone_folder: c:\projects\pythonirbis

test_script:
- cmd: >-
    cd c:\projects\pythonirbis

    call build.cmd

build: off

artifacts:
- path: htmlcov
  name: Coverage
- path: dist
  name: dist
