version: 0.0.{build}
image: Visual Studio 2017

clone_folder: c:\projects\pythonirbis

environment:
  PYTHONPATH: c:\projects\pythonirbis
  PATH: C:\Python36-x64;C:\Python36-x64\Scripts;%PATH%
  PYTHON: C:\Python36-x64\python.exe
  PIP: C:\Python36-x64\Scripts\pip.exe
  COVERAGE: C:\Python36-x64\Scripts\coverage.exe
  TWINE: C:\Python36-x64\Scripts\twine.exe
  TWINE_USERNAME: amironov73
  TWINE_PASSWORD: 
    secure: 1JY9Dr54nOTpD3EAV4mqMQ==
  TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/

install:
  - python -m pip install --upgrade pip
  - pip install --upgrade setuptools wheel coverage mypy twine pylint

before_build:
  - python utils\patch_version.py pyirbis\__init__.py %APPVEYOR_BUILD_VERSION%
  - python utils\patch_version.py setup.py %APPVEYOR_BUILD_VERSION%

build_script:
  - cd c:\projects\pythonirbis
  - python -m mypy pyirbis\core.py
  - python -m mypy pyirbis\ext.py
  - python -m pylint pyirbis\core.py
  - python -m pylint pyirbis\ext.py
  - python -m pylint pyirbis\iso2709.py
  - python -m pylint pyirbis\export.py

after_build:
  - cd c:\projects\pythonirbis
  - python setup.py sdist bdist_wheel

test_script:
  - cd c:\projects\pythonirbis
  - coverage run tests\offline_tests.py
  - coverage report
  - coverage html

after_test:
  - cd c:\projects\pythonirbis
  - twine upload dist/*

artifacts:
  - path: htmlcov
    name: Coverage
  - path: dist
    name: dist
