name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel coverage mypy twine pylint flake8 pytest
    - name: Lint
      run: |
        ./utils/countlines
        flake8 --version
        flake8 irbis/ --ignore=E261,E302,W503,W504 --show-source --statistics
        mypy --version
        mypy irbis/
        pylint --version
        pylint irbis/
    - name: Test
      run: |
        PYTHONPATH=$(pwd) python -m coverage run tests/offline_tests.py
        python -m coverage report
        python -m coverage html
