name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel coverage mypy twine pylint flake8 pytest
    - name: Lint
      run: |
        flake8 --version
        flake8 irbis/ --ignore=E261,E302,W503,W504 --show-source --statistics
        mypy --version
        source mypy0 irbis/
        pylint --version
        source pylint0 irbis/
    - name: Test with pytest
      run: python -m pytest tests/offline_tests.py
