name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel coverage mypy twine pylint flake8 pytest
    - name: Lint with flake8
      run: |
        flake8 irbis/ --count --ignore=E261,E302,E501 --show-source --statistics
        python -m mypy irbis/core.py
        python -m mypy irbis/ext.py
        python -m pylint irbis/core.py
        python -m pylint irbis/ext.py
    - name: Test with pytest
      run: python -m pytest tests/offline_tests.py
